// 389. Find the Difference
// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:
// Input: s = "", t = "y"
// Output: "y"

import java.util.Arrays;

public class FindStrDifference {

    public char findTheDifference(String s, String t) {
        int sum = 0;
        for (char c: t.toCharArray()) sum += c;
        for (char c: s.toCharArray()) sum -= c;
        return (char)sum;
    }

    public char findTheDifferenceLazy(String s, String t) {
        char[] strs = s.toCharArray();
        char[] tstrs = t.toCharArray();
        Arrays.sort(strs);
        Arrays.sort(tstrs);

        for (int i = 0; i < strs.length; i++) {
            if (strs[i] != tstrs[i])
                return tstrs[i];
        }
        return tstrs[tstrs.length - 1];
    }
}
