-- 175. Combine Two Tables
SELECT p.firstName, 
       p.lastName, 
       a.city, 
       a.state
FROM Person p
LEFT JOIN Address a 
ON p.personId = a.personId;

-- 176. Second Highest Salary
SELECT MAX(salary) as SecondHighestSalary FROM Employee WHERE salary != (SELECT MAX(salary) FROM Employee);

-- 181. Employees Earning More Than Their Managers
SELECT e.name as Employee FROM Employee e 
JOIN Employee m ON m.id = e.managerID
WHERE e.salary > m.salary;

-- 182. Duplicate Emails
SELECT email as Email FROM Person 
GROUP BY email
HAVING COUNT(email) > 1;

-- 183. Customers Who Never Order
SELECT c.name as Customers FROM Customers c 
WHERE id NOT IN (SELECT customerId FROM Orders);

-- 196. Delete Duplicate Emails
DELETE  FROM Person
WHERE id NOT IN (
    SELECT MIN(id) FROM Person
    GROUP BY email
);

-- 577. Employee Bonus
SELECT E.NAME, B.BONUS
FROM EMPLOYEE E
FULL OUTER JOIN BONUS B ON E.EMPID = B.EMPID
WHERE B.BONUS < 1000 OR B.BONUS IS NULL;

-- 584. Find Customer Referee
SELECT NAME
FROM CUSTOMER
WHERE REFEREE_ID IS NULL OR REFEREE_ID != 2;

-- 595. Big Countries
SELECT NAME, POPULATION, AREA
FROM WORLD
WHERE AREA >= 3000000 OR POPULATION >= 25000000;

-- 511. Game Play Analysis I
SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_LOGIN 
FROM ACTIVITY A1
GROUP BY PLAYER_ID;

-- 627. Swap Sex of Employees
UPDATE SALARY
SET SEX = CASE 
    WHEN SEX = 'm' THEN 'f'
    WHEN SEX = 'f' THEN 'm'
END;

-- 1075. Project Employees I
SELECT P.PROJECT_ID, ROUND(AVG(E.EXPERIENCE_YEARS), 2) AS AVERAGE_YEARS
FROM PROJECT P
JOIN EMPLOYEE E ON E.EMPLOYEE_ID = P.EMPLOYEE_ID
GROUP BY P.PROJECT_ID;

-- 184. Department Highest Salary
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY
FROM EMPLOYEE E
JOIN (
    SELECT DEPARTMENTID, MAX(SALARY) AS MAX_SALARY 
    FROM EMPLOYEE 
    GROUP BY DEPARTMENTID
) M ON M.DEPARTMENTID = E.DEPARTMENTID AND E.SALARY = M.MAX_SALARY
JOIN DEPARTMENT D ON D.ID = E.DEPARTMENTID;

-- SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY
-- FROM DEPARTMENT D
-- JOIN EMPLOYEE E ON E.DEPARTMENTID = D.ID
-- WHERE E.SALARY IN (
--     SELECT MAX(EMP.SALARY) FROM EMPLOYEE EMP WHERE EMP.DEPARTMENTID = D.ID
-- );

-- 586. Customer Placing the Largest Number of Orders
SELECT CUSTOMER_NUMBER
FROM ORDERS
GROUP BY CUSTOMER_NUMBER
ORDER BY COUNT(*) DESC
LIMIT 1;

-- 596. Classes With at Least 5 Students
SELECT C.CLASS
FROM COURSES C
GROUP BY C.CLASS
HAVING COUNT(STUDENT) >= 5;

-- 602. Friend Requests II: Who Has the Most Friends
SELECT ID, COUNT(*) AS NUM
FROM (
    SELECT REQUESTER_ID AS ID FROM REQUESTACCEPTED
    UNION ALL
    SELECT ACCEPTER_ID AS ID FROM REQUESTACCEPTED
)
GROUP BY ID
ORDER BY NUM DESC
LIMIT 1;

-- 607. Sales Person
SELECT NAME
FROM SALESPERSON
WHERE SALES_ID NOT IN (
    SELECT O.SALES_ID
    FROM ORDERS O
    JOIN COMPANY C ON C.COM_ID = O.COM_ID
    WHERE C.NAME = 'RED' 
);

-- 620. Not Boring Movies
SELECT *
FROM CINEMA
WHERE ID % 2 = 1 AND DESCRIPTION != 'boring'
ORDER BY RATING DESC;

-- 1050. Actors and Directors Who Cooperated At Least Three Times
SELECT ACTOR_ID, DIRECTOR_ID
FROM ACTORDIRECTOR
GROUP BY (ACTOR_ID, DIRECTOR_ID)
HAVING COUNT(TIMESTAMP) >= 3;

-- 1068. Product Sales Analysis I
SELECT P.PRODUCT_NAME, S.YEAR, S.PRICE
FROM PRODUCT P, SALES S WHERE S.PRODUCT_ID = P.PRODUCT_ID;

-- SELECT P.PRODUCT_NAME, S.YEAR, S.PRICE
-- FROM PRODUCT P
-- JOIN SALES S ON S.PRODUCT_ID = P.PRODUCT_ID;