-- 175. Combine Two Tables
SELECT p.firstName, 
       p.lastName, 
       a.city, 
       a.state
FROM Person p
LEFT JOIN Address a 
ON p.personId = a.personId;

-- 176. Second Highest Salary
SELECT MAX(salary) as SecondHighestSalary FROM Employee WHERE salary != (SELECT MAX(salary) FROM Employee);

-- 181. Employees Earning More Than Their Managers
SELECT e.name as Employee FROM Employee e 
JOIN Employee m ON m.id = e.managerID
WHERE e.salary > m.salary;

-- 182. Duplicate Emails
SELECT email as Email FROM Person 
GROUP BY email
HAVING COUNT(email) > 1;

-- 183. Customers Who Never Order
SELECT c.name as Customers FROM Customers c 
WHERE id NOT IN (SELECT customerId FROM Orders);

-- 196. Delete Duplicate Emails
DELETE  FROM Person
WHERE id NOT IN (
    SELECT MIN(id) FROM Person
    GROUP BY email
);

-- 577. Employee Bonus
SELECT E.NAME, B.BONUS
FROM EMPLOYEE E
FULL OUTER JOIN BONUS B ON E.EMPID = B.EMPID
WHERE B.BONUS < 1000 OR B.BONUS IS NULL;

-- 584. Find Customer Referee
SELECT NAME
FROM CUSTOMER
WHERE REFEREE_ID IS NULL OR REFEREE_ID != 2;

-- 595. Big Countries
SELECT NAME, POPULATION, AREA
FROM WORLD
WHERE AREA >= 3000000 OR POPULATION >= 25000000;

-- 511. Game Play Analysis I
SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_LOGIN 
FROM ACTIVITY A1
GROUP BY PLAYER_ID;

-- 627. Swap Sex of Employees
UPDATE SALARY
SET SEX = CASE 
    WHEN SEX = 'm' THEN 'f'
    WHEN SEX = 'f' THEN 'm'
END;

-- 1075. Project Employees I
SELECT P.PROJECT_ID, ROUND(AVG(E.EXPERIENCE_YEARS), 2) AS AVERAGE_YEARS
FROM PROJECT P
JOIN EMPLOYEE E ON E.EMPLOYEE_ID = P.EMPLOYEE_ID
GROUP BY P.PROJECT_ID;

-- 184. Department Highest Salary
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY
FROM EMPLOYEE E
JOIN (
    SELECT DEPARTMENTID, MAX(SALARY) AS MAX_SALARY 
    FROM EMPLOYEE 
    GROUP BY DEPARTMENTID
) M ON M.DEPARTMENTID = E.DEPARTMENTID AND E.SALARY = M.MAX_SALARY
JOIN DEPARTMENT D ON D.ID = E.DEPARTMENTID;

-- SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY
-- FROM DEPARTMENT D
-- JOIN EMPLOYEE E ON E.DEPARTMENTID = D.ID
-- WHERE E.SALARY IN (
--     SELECT MAX(EMP.SALARY) FROM EMPLOYEE EMP WHERE EMP.DEPARTMENTID = D.ID
-- );

-- 586. Customer Placing the Largest Number of Orders
SELECT CUSTOMER_NUMBER
FROM ORDERS
GROUP BY CUSTOMER_NUMBER
ORDER BY COUNT(*) DESC
LIMIT 1;

-- 596. Classes With at Least 5 Students
SELECT C.CLASS
FROM COURSES C
GROUP BY C.CLASS
HAVING COUNT(STUDENT) >= 5;

-- 602. Friend Requests II: Who Has the Most Friends
SELECT ID, COUNT(*) AS NUM
FROM (
    SELECT REQUESTER_ID AS ID FROM REQUESTACCEPTED
    UNION ALL
    SELECT ACCEPTER_ID AS ID FROM REQUESTACCEPTED
)
GROUP BY ID
ORDER BY NUM DESC
LIMIT 1;

-- 607. Sales Person
SELECT NAME
FROM SALESPERSON
WHERE SALES_ID NOT IN (
    SELECT O.SALES_ID
    FROM ORDERS O
    JOIN COMPANY C ON C.COM_ID = O.COM_ID
    WHERE C.NAME = 'RED' 
);

-- 620. Not Boring Movies
SELECT *
FROM CINEMA
WHERE ID % 2 = 1 AND DESCRIPTION != 'boring'
ORDER BY RATING DESC;

-- 1050. Actors and Directors Who Cooperated At Least Three Times
SELECT ACTOR_ID, DIRECTOR_ID
FROM ACTORDIRECTOR
GROUP BY (ACTOR_ID, DIRECTOR_ID)
HAVING COUNT(TIMESTAMP) >= 3;

-- 1068. Product Sales Analysis I
SELECT P.PRODUCT_NAME, S.YEAR, S.PRICE
FROM PRODUCT P, SALES S WHERE S.PRODUCT_ID = P.PRODUCT_ID;

-- SELECT P.PRODUCT_NAME, S.YEAR, S.PRICE
-- FROM PRODUCT P
-- JOIN SALES S ON S.PRODUCT_ID = P.PRODUCT_ID;

-- 1084. Sales Analysis III
SELECT P.PRODUCT_ID, P.PRODUCT_NAME
FROM PRODUCT P, SALES S
WHERE P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
HAVING MIN(s.sale_date)>= '2019-01-01' AND MAX(s.sale_date)<= '2019-03-31';

-- 1148. Article Views I
SELECT AUTHOR_ID AS ID
FROM VIEWS
WHERE AUTHOR_ID = VIEWER_ID
GROUP BY AUTHOR_ID
HAVING COUNT(AUTHOR_ID) >= 1
ORDER BY ID;

-- 619. Biggest Single Number
SELECT MAX(NUM) AS NUM
FROM MYNUMBERS
WHERE NUM IN (
    SELECT NUM
    FROM MYNUMBERS
    GROUP BY NUM
    HAVING COUNT(NUM) = 1
);

-- 1179. Reformat Department Table
SELECT 
    id,
    SUM(CASE WHEN month = 'Jan' THEN revenue END) AS Jan_Revenue,
    SUM(CASE WHEN month = 'Feb' THEN revenue END) AS Feb_Revenue,
    SUM(CASE WHEN month = 'Mar' THEN revenue END) AS Mar_Revenue,
    SUM(CASE WHEN month = 'Apr' THEN revenue END) AS Apr_Revenue,
    SUM(CASE WHEN month = 'May' THEN revenue END) AS May_Revenue,
    SUM(CASE WHEN month = 'Jun' THEN revenue END) AS Jun_Revenue,
    SUM(CASE WHEN month = 'Jul' THEN revenue END) AS Jul_Revenue,
    SUM(CASE WHEN month = 'Aug' THEN revenue END) AS Aug_Revenue,
    SUM(CASE WHEN month = 'Sep' THEN revenue END) AS Sep_Revenue,
    SUM(CASE WHEN month = 'Oct' THEN revenue END) AS Oct_Revenue,
    SUM(CASE WHEN month = 'Nov' THEN revenue END) AS Nov_Revenue,
    SUM(CASE WHEN month = 'Dec' THEN revenue END) AS Dec_Revenue
FROM Department
GROUP BY id;

-- 1327. List the Products Ordered in a Period
SELECT P.PRODUCT_NAME, SUM(O.UNIT) AS UNIT
FROM PRODUCTS P
JOIN ORDERS O ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.ORDER_DATE BETWEEN '2020-02-01' AND '2020-02-29'
GROUP BY P.PRODUCT_NAME
HAVING SUM(O.UNIT) >= 100;

-- 1527. Patients With a Condition
SELECT *
FROM PATIENTS
WHERE CONDITIONS LIKE 'DIAB1%'
OR CONDITIONS LIKE '% DIAB1%';

-- 2356. Number of Unique Subjects Taught by Each Teacher
SELECT TEACHER_ID, COUNT(DISTINCT SUBJECT_ID) AS CNT
FROM TEACHER
GROUP BY TEACHER_ID;

-- 1757. Recyclable and Low Fat Products
SELECT PRODUCT_ID
FROM PRODUCTS 
WHERE LOW_FATS = 'Y' AND RECYCLABLE = 'Y';

-- 1693. Daily Leads and Partners
SELECT DATE_ID, MAKE_NAME, COUNT(DISTINCT LEAD_ID) AS UNIQUE_LEADS, COUNT(DISTINCT PARTNER_ID) AS UNIQUE_PARTNERS
FROM DAILYSALES
GROUP BY DATE_ID, MAKE_NAME;

-- 1683. Invalid Tweets

SELECT TWEET_ID
FROM TWEETS
WHERE CHAR_LENGTH(CONTENT) > 15;

-- 1890. The Latest Login in 2020
SELECT USER_ID, MAX(TIME_STAMP) AS LAST_STAMP
FROM LOGINS
WHERE DATE(TIME_STAMP) BETWEEN DATE('2020-01-01') AND DATE('2020-12-31')
GROUP BY USER_ID;

-- 1393. Capital Gain/Loss
SELECT STOCK_NAME,
SUM(CASE WHEN OPERATION = 'Buy' THEN -PRICE ELSE PRICE END) AS CAPITAL_GAIN_LOSS
FROM STOCKS
GROUP BY STOCK_NAME;

-- 178. Rank Scores
SELECT score, DENSE_RANK() OVER (ORDER BY score DESC) AS RANK 
FROM Scores 
ORDER BY score DESC;

-- 180. Consecutive Numbers
SELECT DISTINCT NUM AS ConsecutiveNums 
FROM (
    SELECT 
        NUM,
        LEAD(NUM, 1) OVER (ORDER BY ID) NEXT_NUM,
        LEAD(NUM, 2) OVER (ORDER BY ID) NEXT_NEXT_NUM
    FROM LOGS
) WHERE NUM = NEXT_NUM AND NUM = NEXT_NEXT_NUM;

-- SELECT DISTINCT L1.NUM AS ConsecutiveNums 
-- FROM LOGS L1
-- JOIN LOGS L2 ON L2.ID = L1.ID + 1
-- JOIN LOGS L3 ON L3.ID = L1.ID + 2
-- WHERE L1.NUM = L2.NUM AND L2.NUM = L3.NUM;

-- 185. Department Top Three Salaries
SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM (
    SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY AS SALARY,
    DENSE_RANK() OVER(
        PARTITION BY D.NAME ORDER BY E.SALARY DESC
    ) AS RANKS
    FROM EMPLOYEE E
    JOIN DEPARTMENT D ON D.ID = E.DEPARTMENTID
)
WHERE RANKS <= 3;

-- 177. Nth Highest Salary
CREATE OR REPLACE FUNCTION NthHighestSalary(N INT) RETURNS TABLE (Salary INT) AS $$
BEGIN
  RETURN QUERY 
    SELECT DISTINCT SUB.SALARY 
    FROM (
        SELECT E.SALARY, 
        DENSE_RANK() OVER (ORDER BY E.SALARY DESC) AS RANKS
        FROM EMPLOYEE E
    ) AS SUB
    WHERE SUB.RANKS = N;
END;
$$ LANGUAGE plpgsql;

-- 1251. Average Selling Price
SELECT P.PRODUCT_ID, 
COALESCE(ROUND(SUM(P.PRICE * U.UNITS) / SUM(U.UNITS)::NUMERIC, 2), 0) AS AVERAGE_PRICE
FROM PRICES P 
LEFT JOIN UNITSSOLD U ON U.PRODUCT_ID = P.PRODUCT_ID 
AND U.PURCHASE_DATE BETWEEN P.START_DATE AND  P.END_DATE
GROUP BY P.PRODUCT_ID;

-- 197. Rising Temperature
WITH NEW_WEATHER AS (
    SELECT ID, RECORDDATE, TEMPERATURE, 
    LAG(RECORDDATE) OVER (ORDER BY RECORDDATE) AS PREV_DATE,
    LAG(TEMPERATURE) OVER (ORDER BY RECORDDATE) AS YESTERDAY_TEMP
    FROM WEATHER
)

SELECT ID 
FROM NEW_WEATHER
WHERE YESTERDAY_TEMP < TEMPERATURE
AND RECORDDATE = PREV_DATE +  INTERVAL '1 DAY';

-- 1211. Queries Quality and Percentage
SELECT QUERY_NAME, 
ROUND(AVG(RATING / POSITION :: NUMERIC), 2) AS QUALITY,
ROUND(
    SUM (CASE WHEN RATING < 3 THEN 1 ELSE 0 END) * 100 / COUNT(*) :: NUMERIC, 2
) AS POOR_QUERY_PERCENTAGE
FROM QUERIES
GROUP BY QUERY_NAME;

-- 1741. Find Total Time Spent by Each Employee
SELECT EVENT_DAY AS DAY, EMP_ID, SUM(OUT_TIME - IN_TIME) AS TOTAL_TIME
FROM EMPLOYEES
GROUP BY EVENT_DAY, EMP_ID;

-- 1378. Replace Employee ID With The Unique Identifier
SELECT EUNI.UNIQUE_ID, E.NAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEEUNI EUNI ON E.ID = EUNI.ID;